### ISSUE TITLE
Починить кэш пользователей

### ISSUE THREAD

**Issue by AlexanderNest** [AlexanderNest/client-revenue-analyzer#101]
В классе ru.nesterov.integration.ClientRevenueAnalyzerIntegrationClient#getUserByUsername есть кэш. Если пользователь в первый раз не был зарегистирован, а потом зарегистрировался, он все еще не будет считаться зарегистрированным, потому что кэш не обновился. Возможно, это не правильно и если возвращается null, оно не кэшируется. Надо это проверить и исправить, если ошибка подтвердится

**Comment by NickTolm** [comment]
для воспроизведения:
1. настроить интеграцию с телеграмом
2. кинуть любое сообщение
3. зарегистироваться
4. кинуть еще раз и тут по идее надо будет еще раз просить регистроваться, хотя мы уже зарегистрировались на шаге 3
